### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by abhinaba1080** [Morcatko/synctractor#1]
Hi , I am getting below error:

```
E/configParser - ReferenceError: window is not defined
[e2e-smoke]     at Object.<anonymous> (C:\Dev Room\Dev\node_modules\synctractor\dist\testability.js:3:24)
```

Note: I am using synctractor codes in onPrepare function in my protractor config file as :

 ```
 onPrepare: () => {
        // browser.ignoreSynchronization = true;
        //browser.waitForAngularEnabled(false);
        synctractor.init();
        synctractor.monitorFetch();
        synctractor.monitorTimeout((_, t) => t !== 11000);
    },
```

**Comment by Morcatko** [comment]
Hi, you need to put this code into your app code, not test config

> 3. Add this as the very first lines of your app entry point:
> ```
> import * as synctractor from 'synctractor';
> synctractor.init();
> synctractor.monitorFetch();
> synctractor.monitorTimeout((_, t) => t !== 11000); 
> ```

**Comment by abhinaba1080** [comment]
@Morcatko I have tried using the same in the app entry point as well.  I am getting the same error. Can you provide a valid example in windows platform?

**Comment by Morcatko** [comment]
Windows is not relevant here as it runs in a browser. Check examples folder
